#[cfg(test)]
use super::common::SESSION_IMPORT_MAX_COUNT;
use super::common::SessionFileCandidate;
use super::common::detect_recent_sessions;
use crate::sessions::ExternalAgentSessionMigration;
use std::fs;
use std::io;
use std::path::Path;

pub fn detect_recent_cla_sessions(
    external_agent_home: &Path,
    codex_home: &Path,
) -> io::Result<Vec<ExternalAgentSessionMigration>> {
    let projects_root = external_agent_home.join("projects");
    if !projects_root.is_dir() {
        return Ok(Vec::new());
    }

    let mut candidates = Vec::new();
    for project_entry in fs::read_dir(projects_root)? {
        let Ok(project_entry) = project_entry else {
            continue;
        };
        let project_path = project_entry.path();
        if !project_path.is_dir() {
            continue;
        }
        let Ok(entries) = fs::read_dir(project_path) else {
            continue;
        };
        for entry in entries {
            let Ok(entry) = entry else {
                continue;
            };
            let path = entry.path();
            if path.extension().and_then(|value| value.to_str()) != Some("jsonl") {
                continue;
            }
            candidates.push(SessionFileCandidate {
                path,
                fallback_cwd: None,
            });
        }
    }
    detect_recent_sessions(codex_home, candidates, /*require_existing_cwd*/ true)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::sessions::ledger::record_imported_session;
    use codex_protocol::ThreadId;
    use serde_json::Value as JsonValue;
    use std::fs::FileTimes;
    use std::fs::OpenOptions;
    use std::path::Path;
    use std::time::Duration;
    use std::time::SystemTime;
    use tempfile::TempDir;

    #[test]
    fn detects_recent_sessions_with_existing_roots() {
        let root = TempDir::new().expect("tempdir");
        let external_agent_home = root.path().join(".external");
        let project_root = root.path().join("repo");
        let session_path = write_session(
            &external_agent_home,
            &project_root,
            "session.jsonl",
            &[
                record("user", "hello there", project_root.as_path()),
                record("assistant", "ack", project_root.as_path()),
            ],
        );

        let sessions =
            detect_recent_cla_sessions(&external_agent_home, root.path()).expect("detect");

        assert_eq!(
            sessions,
            vec![ExternalAgentSessionMigration {
                path: session_path,
                cwd: project_root,
                title: Some("hello there".to_string()),
            }]
        );
    }

    #[test]
    fn prefers_latest_custom_title_over_first_user_message() {
        let root = TempDir::new().expect("tempdir");
        let external_agent_home = root.path().join(".external");
        let project_root = root.path().join("repo");
        let session_path = write_session(
            &external_agent_home,
            &project_root,
            "session.jsonl",
            &[
                record("user", "hello there", project_root.as_path()),
                custom_title_record("first title"),
                custom_title_record("final title"),
            ],
        );

        let sessions =
            detect_recent_cla_sessions(&external_agent_home, root.path()).expect("detect");

        assert_eq!(
            sessions,
            vec![ExternalAgentSessionMigration {
                path: session_path,
                cwd: project_root,
                title: Some("final title".to_string()),
            }]
        );
    }

    #[test]
    fn detects_ai_title_over_first_user_message() {
        let root = TempDir::new().expect("tempdir");
        let external_agent_home = root.path().join(".external");
        let project_root = root.path().join("repo");
        let session_path = write_session(
            &external_agent_home,
            &project_root,
            "session.jsonl",
            &[
                record("user", "hello there", project_root.as_path()),
                ai_title_record("generated by source app"),
            ],
        );

        let sessions =
            detect_recent_cla_sessions(&external_agent_home, root.path()).expect("detect");

        assert_eq!(
            sessions,
            vec![ExternalAgentSessionMigration {
                path: session_path,
                cwd: project_root,
                title: Some("generated by source app".to_string()),
            }]
        );
    }

    #[test]
    fn prefers_custom_title_over_later_ai_title() {
        let root = TempDir::new().expect("tempdir");
        let external_agent_home = root.path().join(".external");
        let project_root = root.path().join("repo");
        let session_path = write_session(
            &external_agent_home,
            &project_root,
            "session.jsonl",
            &[
                record("user", "hello there", project_root.as_path()),
                custom_title_record("custom title"),
                ai_title_record("generated title"),
            ],
        );

        let sessions =
            detect_recent_cla_sessions(&external_agent_home, root.path()).expect("detect");

        assert_eq!(
            sessions,
            vec![ExternalAgentSessionMigration {
                path: session_path,
                cwd: project_root,
                title: Some("custom title".to_string()),
            }]
        );
    }

    #[test]
    fn uses_file_modification_time_for_recency() {
        let root = TempDir::new().expect("tempdir");
        let external_agent_home = root.path().join(".external");
        let project_root = root.path().join("repo");
        let session_path = write_session(
            &external_agent_home,
            &project_root,
            "session.jsonl",
            &[record_at(
                "user",
                "hello",
                &project_root,
                "2020-01-01T00:00:00Z",
            )],
        );

        let sessions =
            detect_recent_cla_sessions(&external_agent_home, root.path()).expect("detect");

        assert_eq!(
            sessions,
            vec![ExternalAgentSessionMigration {
                path: session_path,
                cwd: project_root,
                title: Some("hello".to_string()),
            }]
        );
    }

    #[test]
    fn ignores_sessions_with_old_file_modification_time() {
        let root = TempDir::new().expect("tempdir");
        let external_agent_home = root.path().join(".external");
        let project_root = root.path().join("repo");
        let session_path = write_session(
            &external_agent_home,
            &project_root,
            "session.jsonl",
            &[record("user", "hello", &project_root)],
        );
        set_modified_at(
            &session_path,
            SystemTime::UNIX_EPOCH + Duration::from_secs(/*secs*/ 1),
        );

        assert!(
            detect_recent_cla_sessions(&external_agent_home, root.path())
                .expect("detect")
                .is_empty()
        );
    }

    #[test]
    fn detects_sessions_in_batches() {
        let root = TempDir::new().expect("tempdir");
        let external_agent_home = root.path().join(".external");
        let project_root = root.path().join("repo");
        let timestamp = chrono::Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Secs, true);
        let modified_at = SystemTime::now();
        let mut expected = Vec::new();
        for index in 0..=SESSION_IMPORT_MAX_COUNT {
            let file_name = format!("{index:02}-session.jsonl");
            let title = format!("session {index}");
            let path = write_session(
                &external_agent_home,
                &project_root,
                &file_name,
                &[record_at("user", &title, &project_root, &timestamp)],
            );
            set_modified_at(
                &path,
                modified_at - Duration::from_secs(/*secs*/ index as u64),
            );
            expected.push(ExternalAgentSessionMigration {
                path,
                cwd: project_root.clone(),
                title: Some(title),
            });
        }
        let oldest_session = expected.pop().expect("oldest session");
        let mut all_sessions = expected.clone();
        all_sessions.push(oldest_session.clone());

        let sessions =
            detect_recent_cla_sessions(&external_agent_home, root.path()).expect("detect");

        assert_eq!(sessions, expected);
        for session in sessions {
            record_imported_session(root.path(), &session.path, ThreadId::new())
                .expect("record import");
        }

        let sessions =
            detect_recent_cla_sessions(&external_agent_home, root.path()).expect("detect");

        assert_eq!(sessions, vec![oldest_session.clone()]);
        for session in sessions {
            record_imported_session(root.path(), &session.path, ThreadId::new())
                .expect("record import");
        }

        let changed_at = SystemTime::now()
            + Duration::from_secs(/*secs*/ SESSION_IMPORT_MAX_COUNT as u64 + 1);
        for (index, session) in all_sessions.iter().enumerate() {
            let title = session.title.as_deref().expect("session title");
            std::fs::write(
                &session.path,
                jsonl(&[
                    record("user", title, &project_root),
                    record("assistant", "updated", &project_root),
                ]),
            )
            .expect("update session");
            set_modified_at(
                &session.path,
                changed_at - Duration::from_secs(/*secs*/ index as u64),
            );
        }

        let sessions =
            detect_recent_cla_sessions(&external_agent_home, root.path()).expect("detect");

        assert_eq!(sessions, expected);
        for session in sessions {
            record_imported_session(root.path(), &session.path, ThreadId::new())
                .expect("record import");
        }

        let sessions =
            detect_recent_cla_sessions(&external_agent_home, root.path()).expect("detect");

        assert_eq!(sessions, vec![oldest_session]);
    }

    #[test]
    fn skips_already_imported_current_session_versions() {
        let root = TempDir::new().expect("tempdir");
        let external_agent_home = root.path().join(".external");
        let project_root = root.path().join("repo");
        let session_path = write_session(
            &external_agent_home,
            &project_root,
            "session.jsonl",
            &[record("user", "hello there", project_root.as_path())],
        );

        record_imported_session(root.path(), &session_path, ThreadId::new())
            .expect("record import");

        assert!(
            detect_recent_cla_sessions(&external_agent_home, root.path())
                .expect("detect")
                .is_empty()
        );
    }

    #[test]
    fn redetects_sessions_when_source_contents_change_after_import() {
        let root = TempDir::new().expect("tempdir");
        let external_agent_home = root.path().join(".external");
        let project_root = root.path().join("repo");
        let session_path = write_session(
            &external_agent_home,
            &project_root,
            "session.jsonl",
            &[record("user", "hello there", project_root.as_path())],
        );
        record_imported_session(root.path(), &session_path, ThreadId::new())
            .expect("record import");

        std::fs::write(
            &session_path,
            jsonl(&[
                record("user", "hello there", project_root.as_path()),
                record("assistant", "new reply", project_root.as_path()),
            ]),
        )
        .expect("update session");
        set_modified_at(
            &session_path,
            SystemTime::now() + Duration::from_secs(/*secs*/ 1),
        );

        let sessions =
            detect_recent_cla_sessions(&external_agent_home, root.path()).expect("detect");
        assert_eq!(
            sessions,
            vec![ExternalAgentSessionMigration {
                path: session_path,
                cwd: project_root,
                title: Some("hello there".to_string()),
            }]
        );
    }

    fn write_session(
        external_agent_home: &Path,
        project_root: &Path,
        file_name: &str,
        records: &[JsonValue],
    ) -> std::path::PathBuf {
        let projects_dir = external_agent_home.join("projects").join("repo");
        std::fs::create_dir_all(project_root).expect("project root");
        std::fs::create_dir_all(&projects_dir).expect("projects dir");
        let session_path = projects_dir.join(file_name);
        std::fs::write(&session_path, jsonl(records)).expect("session");
        session_path
    }

    fn set_modified_at(path: &Path, modified_at: SystemTime) {
        OpenOptions::new()
            .write(true)
            .open(path)
            .expect("open session")
            .set_times(FileTimes::new().set_modified(modified_at))
            .expect("set session modified time");
    }

    fn record(role: &str, text: &str, cwd: &Path) -> JsonValue {
        let timestamp = chrono::Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Secs, true);
        record_at(role, text, cwd, &timestamp)
    }

    fn record_at(role: &str, text: &str, cwd: &Path, timestamp: &str) -> JsonValue {
        serde_json::json!({
            "type": role,
            "cwd": cwd,
            "timestamp": timestamp,
            "message": { "content": text }
        })
    }

    fn custom_title_record(title: &str) -> JsonValue {
        serde_json::json!({
            "type": "custom-title",
            "customTitle": title,
        })
    }

    fn ai_title_record(title: &str) -> JsonValue {
        serde_json::json!({
            "type": "ai-title",
            "aiTitle": title,
        })
    }

    fn jsonl(records: &[JsonValue]) -> String {
        records
            .iter()
            .map(JsonValue::to_string)
            .collect::<Vec<_>>()
            .join("\n")
    }
}
