// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalAgentConfigDetectParams = {
/**
 * If true, include detection under the user's home directory.
 */
includeHome?: boolean,
/**
 * Zero or more working directories to include for repo-scoped detection.
 */
cwds?: Array<string> | null,
/**
 * Deprecated field retained for compatibility. This field is ignored; use `migrationSource`
 * to select the migration source.
 */
source?: string | null,
/**
 * Optional migration-source selector. Missing or unrecognized values use the default source.
 */
migrationSource?: string | null, };
